
      "Building Load in Tons?  1000\n",
      "Cost per kWh?  .1\n",
      "Run Redundancy Check?  (y/n) y\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Running: Chiller1 --> 70 tons\n",
      "Running: Chiller3 --> 180 tons\n",
      "Running: Chiller4 --> 270 tons\n",
      "Running: Chiller5 --> 80 tons\n",
      "Running: Chiller6 --> 270 tons\n",
      "Running: Chiller8 --> 150 tons\n",
      "N+1 Redundancy check failed\n",
      "Cooling load exceeds Building load\n",
      "Total kWh --> 57.9 kWh\n",
      "Chiller Load --> 1020 Tons\n",
      "Maximum cooling without largest chiller --> 750 tons\n",
      "Daily Cost --> 138.96 $\n",
      "Monthly Cost --> 4168.8 $\n"
     ]
    }
   ],
   "source": [
    "#User input and create chillers dictionaries\n",
    "building_load = float(input(\"Building Load in Tons? \"))\n",
    "costperkwh = float(input(\"Cost per kWh? \"))\n",
    "redundancy_check = input(\"Run Redundancy Check?  (y/n)\")\n",
    "chillers = [\n",
    "    {\"name\" : \"Chiller1\" , \"eff\" : .05 , \"tons\" : 70},\n",
    "    {\"name\" : \"Chiller2\" , \"eff\" : .06 , \"tons\" : 150},\n",
    "    {\"name\" : \"Chiller3\" , \"eff\" : .09 , \"tons\" : 180},\n",
    "    {\"name\" : \"Chiller4\" , \"eff\" : .06 , \"tons\" : 270},\n",
    "    {\"name\" : \"Chiller5\" , \"eff\" : .02 , \"tons\" : 80},\n",
    "    {\"name\" : \"Chiller6\" , \"eff\" : .07 , \"tons\" : 270},\n",
    "    {\"name\" : \"Chiller7\" , \"eff\" : .13 , \"tons\" : 350},\n",
    "    {\"name\" : \"Chiller8\" , \"eff\" : .01 , \"tons\" : 150},\n",
    "]\n",
    "\n",
    "#Chiller Optimizer\n",
    "best_kw = 10000000\n",
    "best_group = None\n",
    "from itertools import combinations \n",
    "#Creates a group for each in range\n",
    "for r in range(1, len(chillers) + 1):\n",
    "    #for each group reset tons and kw\n",
    "    for group in combinations(chillers, r):\n",
    "        total_tons = 0\n",
    "        total_kw = 0\n",
    "        # for each chiller in each group calculate tons and kw, then find total\n",
    "        for chiller in group:\n",
    "            total_tons = total_tons + chiller[\"tons\"]\n",
    "            kw = chiller[\"tons\"] * chiller[\"eff\"]\n",
    "            total_kw = kw + total_kw\n",
    "        #checks if load is greater than building load, checks for minimum kw, sets the group to the best group\n",
    "        if total_tons >=building_load:\n",
    "            if total_kw < best_kw:\n",
    "                best_kw = total_kw\n",
    "                best_group = group\n",
    "                \n",
    "chiller_load = sum(chiller[\"tons\"] for chiller in best_group)\n",
    "for chiller in best_group:\n",
    "    print(\"Running:\", chiller[\"name\"], \"-->\", chiller[\"tons\"],\"tons\")\n",
    "\n",
    "daily_cost = best_kw * costperkwh * 24\n",
    "monthly_cost = daily_cost * 30\n",
    "\n",
    "#Runs N+1 Redundancy Check\n",
    "if redundancy_check == \"y\":\n",
    "    max_cool = max(chiller[\"tons\"] for chiller in best_group)\n",
    "    red_load = chiller_load - max_cool \n",
    "    if red_load >= building_load:\n",
    "        print(\"N+1 Redundancy check passed\")\n",
    "    else:\n",
    "        print(\"N+1 Redundancy check failed\")\n",
    "\n",
    "#Flags if the plant is oversized or undersized for the load\n",
    "if chiller_load > building_load:\n",
    "    print(\"Cooling load exceeds Building load\")\n",
    "elif chiller_load < building_load:\n",
    "    print(\"Building load exceeds Cooling load\")\n",
    "else:\n",
    "    print(\"Building Load Perfectly Matched\")\n",
    "\n",
    "#Prints all values\n",
    "print(\"Total kWh -->\",round(best_kw,2), \"kWh\")\n",
    "print(\"Chiller Load -->\",chiller_load,\"Tons\")\n",
    "print(\"Maximum cooling without largest chiller -->\", red_load, \"tons\")\n",
    "print(\"Daily Cost -->\",round(daily_cost,2), \"$\")\n",
    "print(\"Monthly Cost -->\",round(monthly_cost,2), \"$\")"
   ]
 
